#:schema node_modules/wrangler/config-schema.json
name = "worst-counter-d1"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
services = [{ binding = "SELF", service = "worst-counter-d1" }]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "worst-counter-d1"
database_id = "60003ba7-ebeb-4119-b965-cd8659e43a48"
